name: push action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello
        run: echo "Hello! i'm ${{ github.actor }} and this triggered  by the ${{ github.event_name }}. Workflow ${{ github_workflow }}"
