name: push action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello
        run: echo "Hello! i'm ${{ github.actor }} and this triggered  by the ${{ github.event_name }}. Workflow ${{ github.workflow }}"
      
      - name: Environment
        env:
          TEST: "this test env_var"
          ACTOR: ${{ github.action }}
        run: |
          echo "value -> $TEST"
          echo "My username: $ACTOR, and export var ACTOR and get value from github"
